AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-app
  
  Sample SAM Template for sam-app

Globals:
  Function:
    Timeout: 5
    CodeUri: dist/functions/

Resources:
  Home:
    Type: AWS::Serverless::Function 
    Properties:
      Handler: index
      Runtime: go1.x
      Events:
        Index:
          Type: Api
          Properties:
            RestApiId: !Ref Api
            Path: /
            Method: GET

  Api:
    Type: AWS::Serverless::Api
    Properties:
      StageName: dev

