AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Timeout: 5

Parameters:
  Stage:
    Type: String

Resources:
    SaveMessage:
        Type: AWS::Serverless::Function
        Properties:
            Handler: saveMessage
            CodeUri: dist/functions/
            Runtime: go1.x
